// pages/mealplan/index.js
const { getStorage, setStorage, today } = require('../../utils/storage.js');
const { defaultWeekPlans } = require('../../data/mealPlan.js'); // 获取小程序的周种子数据

Page({
  data: {
    weekPlans: [],
    currentWeekIndex: 0,
    currentWeek: null,
    notes: {}, // 每日食谱大备注存储对象
    isWeekGenerated: false, // 本周食谱是否已经生成
    isLoggedIn: false,      // 用户是否已经登录
    
    // 规则校验结果
    rules: {
      meatPassed: false,
      meatCount: 0,
      fishShrimpLiverCount: 0,
      fishShrimpLiverPassed: false,
      grainPercent: 0,
      grainPassed: false,
      eggDays: 0,
      eggPassed: false,
      namingPassed: true,
      allergenPassed: true,
      allergenLogs: []
    }
  },

  onShow: function () {
    this.setData({ animKey: ((this.data.animKey || 0) + 1) % 2 });
    if (typeof this.getTabBar === 'function' && this.getTabBar()) {
      this.getTabBar().setData({ selected: 1 });
    }
    this.initMealPlans();

    // 静默刷新
    const { syncPull } = require('../../utils/storage.js');
    syncPull('meal_plans', () => {
      this.initMealPlans();
    });
  },

  onPullDownRefresh: function () {
    const { syncPull } = require('../../utils/storage.js');
    syncPull('meal_plans', () => {
      this.initMealPlans();
      wx.stopPullDownRefresh();
    });
  },

  initMealPlans: function () {
    // 获取本地周计划列表，没有则用种子数据
    const list = getStorage('baby_week_plans', defaultWeekPlans);
    const activeIndex = this.data.currentWeekIndex;
    const currentWeek = list[activeIndex] || list[0] || null;

    let isWeekGenerated = false;
    if (currentWeek && currentWeek.days) {
      const todayStr = today();
      currentWeek.days.forEach(day => {
        day.isPassed = day.date < todayStr;
      });
      isWeekGenerated = currentWeek.days.some(day => 
        day.meals && day.meals.some(meal => meal.name && meal.name.trim() !== '')
      );
    }

    const isLoggedIn = !!(wx.getStorageSync('user_is_logged_in') || wx.getStorageSync('user_openid'));

    this.setData({
      weekPlans: list,
      currentWeek: currentWeek,
      currentWeekPeriodChinese: this.formatPeriodToChinese(currentWeek ? currentWeek.period : ''),
      notes: getStorage('meal_day_notes', {}),
      isWeekGenerated: isWeekGenerated,
      isLoggedIn: isLoggedIn
    }, () => {
      this.validateRules();

      if (isLoggedIn) {
        const allergenCompleted = wx.getStorageSync('allergen_setup_completed');
        if (!allergenCompleted) {
          wx.showModal({
            title: '定制个性化辅食食谱',
            content: '在自动排出辅食食谱前，需要先去“排敏食材管理”中勾选确认宝宝已过关与待排敏的食材档案。是否现在前往？',
            confirmText: '去确认',
            cancelText: '暂不',
            success: (res) => {
              if (res.confirm) {
                wx.navigateTo({ url: '/pages/allergen/index' });
              }
            }
          });
        } else {
          const mealPlanAutoGenerated = wx.getStorageSync('meal_plan_auto_generated');
          if (!mealPlanAutoGenerated) {
            this.generateWeekRecipe();
            wx.setStorageSync('meal_plan_auto_generated', true);
          }
        }
      }
    });
  },

  // 切换不同周
  switchWeek: function (e) {
    const direction = e.currentTarget.dataset.dir;
    let index = this.data.currentWeekIndex;
    if (direction === 'prev' && index > 0) {
      index--;
    } else if (direction === 'next' && index < this.data.weekPlans.length - 1) {
      index++;
    }

    const currentWeek = this.data.weekPlans[index];
    let isWeekGenerated = false;
    if (currentWeek && currentWeek.days) {
      const todayStr = today();
      currentWeek.days.forEach(day => {
        day.isPassed = day.date < todayStr;
      });
      isWeekGenerated = currentWeek.days.some(day => 
        day.meals && day.meals.some(meal => meal.name && meal.name.trim() !== '')
      );
    }

    this.setData({
      currentWeekIndex: index,
      currentWeek: currentWeek,
      currentWeekPeriodChinese: this.formatPeriodToChinese(currentWeek ? currentWeek.period : ''),
      isWeekGenerated: isWeekGenerated
    }, () => {
      this.validateRules();
    });
  },

  // 进行排餐规则校验
  validateRules: function () {
    const week = this.data.currentWeek;
    if (!week) return;

    let fishCount = 0;
    let shrimpCount = 0;
    let liverCount = 0;
    let porridgeCount = 0;
    let noodleCount = 0;
    let eggPassed = true;
    let greenVegOkCount = 0;
    let totalMeals = 0;
    let namingPassed = true;
    let allergenPassed = true;
    let allergenLogs = [];

    // 获取当前最新的未排敏食材池，实现与排敏食材管理页面数据的实时打通
    const defaultRiskFoods = [
      { name: '燕麦米' }, { name: '低筋面粉' }, { name: '芋头' }, { name: '芦笋' },
      { name: '白萝卜' }, { name: '紫薯' }, { name: '芹菜' }, { name: '紫甘蓝' },
      { name: '卷心菜' }, { name: '菜花' }, { name: '冬瓜' }, { name: '丝瓜' },
      { name: '苦瓜' }, { name: '梨' }, { name: '蓝莓' }, { name: '桃' },
      { name: '杏' }, { name: '草莓' }, { name: '芒果' }, { name: '猕猴桃' },
      { name: '柑橘' }, { name: '橙子' }, { name: '柚子' }, { name: '西梅' },
      { name: '菠萝' }, { name: '蛋黄' }, { name: '蛋清' }, { name: '鹅肝' },
      { name: '三文鱼' }, { name: '龙利鱼' }, { name: '鲈鱼' }, { name: '带鱼' },
      { name: '黄花鱼' }, { name: '基围虾' }, { name: '螃蟹' }, { name: '豆腐' },
      { name: '奶酪' }, { name: '酸奶' }, { name: '芝麻' }
    ];
    const riskList = getStorage('mp_risk_foods_list', defaultRiskFoods);
    const bannedFoods = riskList.map(f => f.name);

    week.days.forEach(day => {
      // 校验全周每天鸡蛋配额是否在 1-2 个之间
      if (day.eggTarget < 1 || day.eggTarget > 2) {
        eggPassed = false;
      }
      day.meals.forEach(meal => {
        if (!meal.name) return;
        totalMeals++;

        // 1. 校验拼写命名 (不能含 + 号)
        if (meal.name.includes('+')) {
          namingPassed = false;
        }

        // 2. 统计各种食材频次
        if (meal.name.includes('鱼')) fishCount++;
        if (meal.name.includes('虾')) shrimpCount++;
        if (meal.name.includes('肝')) liverCount++;
        if (meal.name.includes('粥')) porridgeCount++;
        if (meal.name.includes('面')) noodleCount++;

        // 3. 校验每餐是否含绿叶菜/青菜
        const greenKeywords = ['青菜', '绿叶菜', '菠菜', '西兰花', '小白菜', '油菜', '生菜', '油麦菜', '上海青', '菜心', '奶白菜'];
        if (greenKeywords.some(kw => meal.name.includes(kw))) {
          greenVegOkCount++;
        }

        // 4. 排查未排敏违禁食物
        bannedFoods.forEach(banned => {
          if (meal.name.includes(banned)) {
            allergenPassed = false;
            allergenLogs.push(`${day.dayName}${meal.type}：${meal.name}（含未排敏食材：${banned}）`);
          }
        });
      });
    });

    const fishPassed = fishCount >= 2 && fishCount <= 3;
    const shrimpPassed = shrimpCount >= 2 && shrimpCount <= 3;
    const liverPassed = liverCount >= 2 && liverCount <= 3;
    const porridgePassed = porridgeCount === 2;
    const noodlePassed = noodleCount === 3;
    const greenVegPassed = greenVegOkCount === totalMeals;

    // 动态装配顶部综合规则合规反馈报告
    const errors = [];
    if (!fishPassed) errors.push(`鱼类频次不合规（当前 ${fishCount} 次，目标 2-3 次）`);
    if (!shrimpPassed) errors.push(`虾类频次不合规（当前 ${shrimpCount} 次，目标 2-3 次）`);
    if (!liverPassed) errors.push(`鹅肝频次不合规（当前 ${liverCount} 次，目标 2-3 次）`);
    if (!porridgePassed) errors.push(`粥频次不合规（当前 ${porridgeCount} 次，目标固定 2 次）`);
    if (!noodlePassed) errors.push(`粗面频次不合规（当前 ${noodleCount} 次，目标固定 3 次）`);
    if (!eggPassed) errors.push(`每日鸡蛋配额不合规（应全周每天 1-2 个）`);
    if (!greenVegPassed) errors.push(`绿叶菜覆盖度不合规（应全周每餐均含绿叶菜）`);
    if (!namingPassed) errors.push('菜品命名包含非法字符（禁止使用"+"号，请以"猪肉香菇青菜烩饭"形式命名）');
    if (!allergenPassed) errors.push('检测到引入了未排敏的风险食材');

    let passed = errors.length === 0;
    let message = '';
    if (passed) {
      message = '🎉 恭喜！当前辅食排餐完全符合所有营养及安全排敏规则，全部达标！';
    } else {
      message = '⚠️ 警报：当前计划存在以下不合规，请检查调整：\n' + errors.map((e, idx) => `（${idx + 1}）${e}`).join('\n');
    }

    this.setData({
      rules: {
        passed: passed,
        message: message,
        meatCount: fishCount + shrimpCount,
        meatPassed: fishPassed && shrimpPassed,
        fishShrimpLiverCount: fishCount + shrimpCount + liverCount,
        fishShrimpLiverPassed: fishPassed && shrimpPassed && liverPassed,
        grainPercent: totalMeals > 0 ? Math.round((porridgeCount / totalMeals) * 100) : 0,
        grainPassed: porridgePassed,
        eggDays: eggPassed ? 7 : 0,
        eggPassed: eggPassed,
        namingPassed: namingPassed,
        allergenPassed: allergenPassed,
        allergenLogs: allergenLogs
      }
    });
  },

  // 修改每日喂养便签备忘录
  updateNote: function (e) {
    const { date, mealtype } = e.currentTarget.dataset;
    const notes = getStorage('meal_notes', {});
    const val = e.detail.value;

    notes[`${date}_${mealtype}`] = val;
    setStorage('meal_notes', notes);
  },

  // 更新并保存每日大备注
  updateDayNote: function (e) {
    const date = e.currentTarget.dataset.date;
    const todayStr = today();
    if (date < todayStr) {
      return;
    }
    const val = e.detail.value;
    const notes = { ...this.data.notes };
    notes[date] = val;
    this.setData({ notes });
    // 本地保存
    wx.setStorageSync('meal_day_notes', notes);
    // 同步到云端 families 文档（与 timer_items、timeline_categories 方式一致）
    const familyId = wx.getStorageSync('user_family_id');
    if (familyId && wx.cloud) {
      wx.cloud.callFunction({
        name: 'updateFamily',
        data: { action: 'update', familyId, data: { meal_day_notes: notes } },
        fail: (err) => { console.warn('meal_day_notes 同步失败:', err); }
      });
    }
  },

  // 就地修改特定辅食食谱菜品
  editMeal: function (e) {
    // 未登录不允许编辑
    if (!wx.getStorageSync('user_is_logged_in') && !wx.getStorageSync('user_openid')) {
      wx.showModal({
        title: '请先登录',
        content: '修改辅食菜品需要先登录，以便数据云端同步保存。',
        confirmText: '去登录',
        success: (res) => { if (res.confirm) wx.navigateTo({ url: '/pages/login/index' }); }
      });
      return;
    }
    const { date, mealtype, name } = e.currentTarget.dataset;
    const that = this;

    wx.showModal({
      title: `修改 ${mealtype} 菜品`,
      content: name || '',
      editable: true,
      placeholderText: '请输入辅食菜品名称（如：泥糊状牛肉小米粥）',
      success: (res) => {
        if (res.confirm) {
          const newName = res.content.trim();
          if (!newName) {
            wx.showToast({ title: '菜品名称不能为空', icon: 'none' });
            return;
          }

          // 读取当前所有周计划
          const list = [...that.data.weekPlans];
          const activeIndex = that.data.currentWeekIndex;
          const currentWeek = list[activeIndex];

          if (!currentWeek) return;

          // 寻找对应天和餐别
          const dayObj = currentWeek.days.find(d => d.date === date);
          if (dayObj) {
            const mealObj = dayObj.meals.find(m => m.type === mealtype);
            if (mealObj) {
              mealObj.name = newName;
            } else {
              // 兜底创建餐别
              dayObj.meals.push({ type: mealtype, name: newName });
            }
          }

          // 写回本地缓存
          setStorage('baby_week_plans', list);
          
          let isWeekGenerated = false;
          if (currentWeek && currentWeek.days) {
            isWeekGenerated = currentWeek.days.some(day => 
              day.meals && day.meals.some(meal => meal.name && meal.name.trim() !== '')
            );
          }

          // 更新页面状态并重新校验
          that.setData({
            weekPlans: list,
            currentWeek: currentWeek,
            isWeekGenerated: isWeekGenerated
          }, () => {
            that.validateRules();
            wx.showToast({ title: '菜品已修改', icon: 'success' });
          });
        }
      }
    });
  },

  // 动态创建下周辅食食谱（依据已排敏食材与营养规则自动智能规划）
  addNewWeek: function () {
    // 未登录不允许新增
    if (!wx.getStorageSync('user_is_logged_in') && !wx.getStorageSync('user_openid')) {
      wx.showModal({
        title: '请先登录',
        content: '新增下周食谱需要先登录，以便数据同步保存至云端数据库。',
        confirmText: '去登录',
        success: (res) => { if (res.confirm) wx.navigateTo({ url: '/pages/login/index' }); }
      });
      return;
    }
    const list = [...this.data.weekPlans];
    const lastWeek = list[list.length - 1];
    
    let lastDateStr = '2026-07-12'; // 默认底线日期
    if (lastWeek && lastWeek.days && lastWeek.days.length > 0) {
      lastDateStr = lastWeek.days[lastWeek.days.length - 1].date;
    }

    const lastDate = new Date(lastDateStr);
    const nextDays = [];
    const weekDaysNames = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'];

    // 获取小程序已排敏食材（打通 allergen 页面）
    const localSafe = getStorage('mp_safe_foods_list', []);
    const safeNames = localSafe.map(f => f.name);

    const fishPool = ['鳕鱼', '比目鱼'].filter(f => safeNames.includes(f));
    const shrimpPool = ['黑虎虾', '北极甜虾'].filter(f => safeNames.includes(f));
    const liverPool = ['鹅肝', '猪肝'].filter(f => safeNames.includes(f));
    const vegPool = ['山药', '红薯', '胡萝卜', '土豆', '莲藕', '西葫芦', '南瓜', '西红柿', '黄瓜'].filter(f => safeNames.includes(f));
    const sidePool = ['蒸糕', '小饼', '馒头'].filter(f => safeNames.includes(f));

    const getFish = () => selectIngredient(fishPool, '鳕鱼');
    const getShrimp = () => selectIngredient(shrimpPool, '鲜虾');
    const getLiver = () => selectIngredient(liverPool, '鹅肝');
    const getSide = (type) => {
      if (type === '蒸糕') return selectIngredient(sidePool.filter(s => s.includes('糕')), '蒸糕');
      if (type === '小饼') return selectIngredient(sidePool.filter(s => s.includes('饼')), '小饼');
      if (type === '馒头') return selectIngredient(sidePool.filter(s => s.includes('馒')), '馒头');
      return selectIngredient(sidePool, type);
    };

    function selectIngredient(arr, fallback) {
      if (arr && arr.length > 0) {
        return arr[Math.floor(Math.random() * arr.length)];
      }
      return fallback;
    }

    function getUniqueVeg(count, fallbacks) {
      const result = [];
      const temp = [...vegPool];
      for (let i = 0; i < count; i++) {
        if (temp.length > 0) {
          const idx = Math.floor(Math.random() * temp.length);
          result.push(temp.splice(idx, 1)[0]);
        } else {
          result.push(fallbacks[i % fallbacks.length]);
        }
      }
      return result;
    }

    // 预生成7天的日期对象
    const dateObjs = [];
    for (let i = 1; i <= 7; i++) {
      const nextDate = new Date(lastDate.getTime() + i * 24 * 60 * 60 * 1000);
      const y = nextDate.getFullYear();
      let m = nextDate.getMonth() + 1;
      let d = nextDate.getDate();
      if (m < 10) m = '0' + m;
      if (d < 10) d = '0' + d;
      dateObjs.push({ dateStr: `${y}-${m}-${d}`, dayName: weekDaysNames[i - 1] });
    }

    // 智能配方逻辑与小程序结构 meals: { type: '午餐', name: '...' } 适配
    // 周一 (Mon): 蛋 1
    {
      const v = getUniqueVeg(1, ['香菇']);
      const monLunch = `猪肉${v[0]}青菜烩饭`;
      const monDinner = `牛肉青菜小米粥、鸡蛋羹`;
      nextDays.push({
        date: dateObjs[0].dateStr, dayName: dateObjs[0].dayName, eggTarget: 1,
        meals: [
          { type: '午餐', name: monLunch },
          { type: '晚餐', name: monDinner }
        ]
      });
    }

    // 周二 (Tue): 蛋 2
    {
      const v = getUniqueVeg(2, ['西葫芦', '南瓜']);
      const tueLunch = `${v[0]}青菜${getShrimp()}粗面（含蛋花）`;
      const tueDinner = `${getFish()}${v[1]}青菜烩饭、蛋饼小块`;
      nextDays.push({
        date: dateObjs[1].dateStr, dayName: dateObjs[1].dayName, eggTarget: 2,
        meals: [
          { type: '午餐', name: tueLunch },
          { type: '晚餐', name: tueDinner }
        ]
      });
    }

    // 周三 (Wed): 蛋 1
    {
      const v = getUniqueVeg(3, ['胡萝卜', '西红柿', '土豆']);
      const wedLunch = `${getLiver()}${v[0]}青菜烩饭、${getSide('蒸糕')}（含蛋）`;
      const wedDinner = `牛肉${v[1]}${v[2]}青菜烩饭`;
      nextDays.push({
        date: dateObjs[2].dateStr, dayName: dateObjs[2].dayName, eggTarget: 1,
        meals: [
          { type: '午餐', name: wedLunch },
          { type: '晚餐', name: wedDinner }
        ]
      });
    }

    // 周四 (Thu): 蛋 1
    {
      const v = getUniqueVeg(1, ['山药']);
      const thuLunch = `${getFish()}${v[0]}青菜烩饭`;
      const thuDinner = `猪肉青菜燕麦米粥、鸡蛋羹`;
      nextDays.push({
        date: dateObjs[3].dateStr, dayName: dateObjs[3].dayName, eggTarget: 1,
        meals: [
          { type: '午餐', name: thuLunch },
          { type: '晚餐', name: thuDinner }
        ]
      });
    }

    // 周五 (Fri): 蛋 2
    {
      const v = getUniqueVeg(2, ['莲藕', '玉米']);
      const friLunch = `牛肉${v[0]}青菜烩饭、${getSide('小饼')}（含蛋）`;
      const friDinner = `${v[1]}青菜${getShrimp()}粗面（含蛋花）`;
      nextDays.push({
        date: dateObjs[4].dateStr, dayName: dateObjs[4].dayName, eggTarget: 2,
        meals: [
          { type: '午餐', name: friLunch },
          { type: '晚餐', name: friDinner }
        ]
      });
    }

    // 周六 (Sat): 蛋 1
    {
      const v = getUniqueVeg(2, ['红薯', '黄瓜']);
      const satLunch = `猪肉${v[0]}豆腐青菜烩饭、蛋黄小块`;
      const satDinner = `${getFish()}${v[1]}青菜烩饭`;
      nextDays.push({
        date: dateObjs[5].dateStr, dayName: dateObjs[5].dayName, eggTarget: 1,
        meals: [
          { type: '午餐', name: satLunch },
          { type: '晚餐', name: satDinner }
        ]
      });
    }

    // 周日 (Sun): 蛋 1
    {
      const v = getUniqueVeg(2, ['胡萝卜', '南瓜']);
      const sunLunch = `${v[0]}青菜${getShrimp()}粗面、${getSide('馒头')}小块`;
      const sunDinner = `${getLiver()}${v[1]}青菜烩饭、鸡蛋羹`;
      nextDays.push({
        date: dateObjs[6].dateStr, dayName: dateObjs[6].dayName, eggTarget: 1,
        meals: [
          { type: '午餐', name: sunLunch },
          { type: '晚餐', name: sunDinner }
        ]
      });
    }

    let nextWeekNum = list.length + 1;
    if (lastWeek && lastWeek.week) {
      const match = lastWeek.week.match(/第\s*(\d+)\s*周辅食计划/);
      if (match) {
        nextWeekNum = parseInt(match[1]) + 1;
      } else if (lastWeek.week === '第一周辅食计划') {
        nextWeekNum = 2;
      }
    }
    const nextWeekName = `第${nextWeekNum}周辅食计划`;
    const startPeriod = nextDays[0].date.slice(5).replace('-', '.');
    const endPeriod = nextDays[6].date.slice(5).replace('-', '.');
    
    const newWeekObj = {
      week: nextWeekName,
      period: `${startPeriod}-${endPeriod}`,
      days: nextDays
    };

    const todayStr = today();
    newWeekObj.days.forEach(day => {
      day.isPassed = day.date < todayStr;
    });

    list.push(newWeekObj);
    
    // 写回缓存并触发静默同步
    setStorage('baby_week_plans', list);

    this.setData({
      weekPlans: list,
      currentWeekIndex: list.length - 1,
      currentWeek: newWeekObj,
      currentWeekPeriodChinese: this.formatPeriodToChinese(newWeekObj.period),
      isWeekGenerated: true
    }, () => {
      this.validateRules();
      wx.showToast({ title: '已开通下周食谱', icon: 'success' });
    });
  },

  // 就地修改特定一天的鸡蛋配额目标
  adjustEggTarget: function (e) {
    // 未登录不允许修改
    if (!wx.getStorageSync('user_is_logged_in') && !wx.getStorageSync('user_openid')) {
      wx.showModal({
        title: '请先登录',
        content: '修改鸡蛋配额需要先登录，以便数据同步保存至云端数据库。',
        confirmText: '去登录',
        success: (res) => { if (res.confirm) wx.navigateTo({ url: '/pages/login/index' }); }
      });
      return;
    }
    const { date, current } = e.currentTarget.dataset;
    const todayStr = today();
    if (date < todayStr) {
      wx.showToast({ title: '已过期的日期无法修改鸡蛋配额', icon: 'none' });
      return;
    }
    const currentTarget = parseInt(current) || 1;
    const nextTarget = currentTarget === 1 ? 2 : 1; // 在 1 个与 2 个之间切换

    const list = [...this.data.weekPlans];
    const activeIndex = this.data.currentWeekIndex;
    const currentWeek = list[activeIndex];
    if (!currentWeek) return;

    const dayObj = currentWeek.days.find(d => d.date === date);
    if (dayObj) {
      dayObj.eggTarget = nextTarget;
    }

    setStorage('baby_week_plans', list);
    this.setData({
      weekPlans: list,
      currentWeek: currentWeek
    }, () => {
      this.validateRules();
      wx.showToast({ title: `鸡蛋已设为 ${nextTarget}个`, icon: 'success' });
    });
  },

  // 格式化日期范围为中文形式
  formatPeriodToChinese: function (period) {
    if (!period) return '';
    const matches = period.match(/(\d{2})[/\.](\d{2})\s*[-—]\s*(\d{2})[/\.](\d{2})/);
    if (matches) {
      const m1 = parseInt(matches[1]);
      const d1 = parseInt(matches[2]);
      const m2 = parseInt(matches[3]);
      const d2 = parseInt(matches[4]);
      return `${m1}月${d1}日到${m2}月${d2}日`;
    }
    const parts = period.split(/[-—]/);
    if (parts.length === 2) {
      const p1 = parts[0].trim().replace('.', '/').split('/');
      const p2 = parts[1].trim().replace('.', '/').split('/');
      if (p1.length === 2 && p2.length === 2) {
        return `${parseInt(p1[0])}月${parseInt(p1[1])}日到${parseInt(p2[0])}月${parseInt(p2[1])}日`;
      }
    }
    return period;
  },

  // 跳转至登录页
  goToLogin: function () {
    wx.navigateTo({ url: '/pages/login/index' });
  },

  // 触发食谱智能生成或重置提示
  triggerRecipeGeneration: function () {
    if (!this.data.isLoggedIn) {
      wx.showModal({
        title: '请先登录',
        content: '智能自动规划本周食谱需要先登录，以便数据同步保存至云端数据库。',
        confirmText: '去登录',
        success: (res) => {
          if (res.confirm) {
            wx.navigateTo({ url: '/pages/login/index' });
          }
        }
      });
      return;
    }
    const that = this;
    wx.showModal({
      title: this.data.isWeekGenerated ? '确定要重置本周食谱吗？' : '确定要智能生成本周食谱吗？',
      content: this.data.isWeekGenerated ? '重置后，本周所有已填写的辅食菜品将被清空并重新智能规划。' : '系统将依据已排敏食材和营养摄入频次规则，自动规划并填满本周辅食菜单。',
      success: (res) => {
        if (res.confirm) {
          that.generateWeekRecipe();
        }
      }
    });
  },

  // 智能生成本周食谱逻辑并同步到数据库
  generateWeekRecipe: function () {
    const list = [...this.data.weekPlans];
    const activeIndex = this.data.currentWeekIndex;
    const currentWeek = list[activeIndex];
    if (!currentWeek) return;

    // 获取小程序已排敏食材（打通 allergen 页面）
    const localSafe = getStorage('mp_safe_foods_list', []);
    const safeNames = localSafe.map(f => f.name);

    const fishPool = ['鳕鱼', '比目鱼'].filter(f => safeNames.includes(f));
    const shrimpPool = ['黑虎虾', '北极甜虾'].filter(f => safeNames.includes(f));
    const liverPool = ['鹅肝', '猪肝'].filter(f => safeNames.includes(f));
    const vegPool = ['山药', '红薯', '胡萝卜', '土豆', '莲藕', '西葫芦', '南瓜', '西红柿', '黄瓜'].filter(f => safeNames.includes(f));
    const sidePool = ['蒸糕', '小饼', '馒头'].filter(f => safeNames.includes(f));

    const getFish = () => selectIngredient(fishPool, '鳕鱼');
    const getShrimp = () => selectIngredient(shrimpPool, '鲜虾');
    const getLiver = () => selectIngredient(liverPool, '鹅肝');
    const getSide = (type) => {
      if (type === '蒸糕') return selectIngredient(sidePool.filter(s => s.includes('糕')), '蒸糕');
      if (type === '小饼') return selectIngredient(sidePool.filter(s => s.includes('饼')), '小饼');
      if (type === '馒头') return selectIngredient(sidePool.filter(s => s.includes('馒')), '馒头');
      return selectIngredient(sidePool, type);
    };

    function selectIngredient(arr, fallback) {
      if (arr && arr.length > 0) {
        return arr[Math.floor(Math.random() * arr.length)];
      }
      return fallback;
    }

    function getUniqueVeg(count, fallbacks) {
      const result = [];
      const temp = [...vegPool];
      for (let i = 0; i < count; i++) {
        if (temp.length > 0) {
          const idx = Math.floor(Math.random() * temp.length);
          result.push(temp.splice(idx, 1)[0]);
        } else {
          result.push(fallbacks[i % fallbacks.length]);
        }
      }
      return result;
    }

    const nextDays = [];
    const daysData = currentWeek.days;

    // 周一 (Mon): 蛋 1
    {
      const v = getUniqueVeg(1, ['香菇']);
      const monLunch = `猪肉${v[0]}青菜烩饭`;
      const monDinner = `牛肉青菜小米粥、鸡蛋羹`;
      const d = daysData[0] || { date: '', dayName: '周一' };
      nextDays.push({
        date: d.date, dayName: d.dayName || '周一', eggTarget: 1,
        meals: [
          { type: '午餐', name: monLunch },
          { type: '晚餐', name: monDinner }
        ]
      });
    }

    // 周二 (Tue): 蛋 2
    {
      const v = getUniqueVeg(2, ['西葫芦', '南瓜']);
      const tueLunch = `${v[0]}青菜${getShrimp()}粗面（含蛋花）`;
      const tueDinner = `${getFish()}${v[1]}青菜烩饭、蛋饼小块`;
      const d = daysData[1] || { date: '', dayName: '周二' };
      nextDays.push({
        date: d.date, dayName: d.dayName || '周二', eggTarget: 2,
        meals: [
          { type: '午餐', name: tueLunch },
          { type: '晚餐', name: tueDinner }
        ]
      });
    }

    // 周三 (Wed): 蛋 1
    {
      const v = getUniqueVeg(3, ['胡萝卜', '西红柿', '土豆']);
      const wedLunch = `${getLiver()}${v[0]}青菜烩饭、${getSide('蒸糕')}（含蛋）`;
      const wedDinner = `牛肉${v[1]}${v[2]}青菜烩饭`;
      const d = daysData[2] || { date: '', dayName: '周三' };
      nextDays.push({
        date: d.date, dayName: d.dayName || '周三', eggTarget: 1,
        meals: [
          { type: '午餐', name: wedLunch },
          { type: '晚餐', name: wedDinner }
        ]
      });
    }

    // 周四 (Thu): 蛋 1
    {
      const v = getUniqueVeg(1, ['山药']);
      const thuLunch = `${getFish()}${v[0]}青菜烩饭`;
      const thuDinner = `猪肉青菜燕麦米粥、鸡蛋羹`;
      const d = daysData[3] || { date: '', dayName: '周四' };
      nextDays.push({
        date: d.date, dayName: d.dayName || '周四', eggTarget: 1,
        meals: [
          { type: '午餐', name: thuLunch },
          { type: '晚餐', name: thuDinner }
        ]
      });
    }

    // 周五 (Fri): 蛋 2
    {
      const v = getUniqueVeg(2, ['莲藕', '玉米']);
      const friLunch = `牛肉${v[0]}青菜烩饭、${getSide('小饼')}（含蛋）`;
      const friDinner = `${v[1]}青菜${getShrimp()}粗面（含蛋花）`;
      const d = daysData[4] || { date: '', dayName: '周五' };
      nextDays.push({
        date: d.date, dayName: d.dayName || '周五', eggTarget: 2,
        meals: [
          { type: '午餐', name: friLunch },
          { type: '晚餐', name: friDinner }
        ]
      });
    }

    // 周六 (Sat): 蛋 1
    {
      const v = getUniqueVeg(2, ['红薯', '黄瓜']);
      const satLunch = `猪肉${v[0]}豆腐青菜烩饭、蛋黄小块`;
      const satDinner = `${getFish()}${v[1]}青菜烩饭`;
      const d = daysData[5] || { date: '', dayName: '周六' };
      nextDays.push({
        date: d.date, dayName: d.dayName || '周六', eggTarget: 1,
        meals: [
          { type: '午餐', name: satLunch },
          { type: '晚餐', name: satDinner }
        ]
      });
    }

    // 周日 (Sun): 蛋 1
    {
      const v = getUniqueVeg(2, ['胡萝卜', '南瓜']);
      const sunLunch = `${v[0]}青菜${getShrimp()}粗面、${getSide('馒头')}小块`;
      const sunDinner = `${getLiver()}${v[1]}青菜烩饭、鸡蛋羹`;
      const d = daysData[6] || { date: '', dayName: '周日' };
      nextDays.push({
        date: d.date, dayName: d.dayName || '周日', eggTarget: 1,
        meals: [
          { type: '午餐', name: sunLunch },
          { type: '晚餐', name: sunDinner }
        ]
      });
    }

    const todayStr = today();
    nextDays.forEach(day => {
      day.isPassed = day.date < todayStr;
    });
    currentWeek.days = nextDays;
    setStorage('baby_week_plans', list); // 会自动触发静默云同步同步到数据库

    this.setData({
      weekPlans: list,
      currentWeek: currentWeek,
      isWeekGenerated: true
    }, () => {
      this.validateRules();
      wx.showToast({ title: '食谱已智能生成', icon: 'success' });
    });
  }
});
